---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: hubot-decard
    service: hubot
    type: decard
  name: hubot-decard-v0
spec:
  replicas: 1
  selector:
    name: hubot-decard
    service: hubot
    type: decard
    version: v0
  template:
    metadata:
      labels:
        name: hubot-decard
        service: hubot
        type: decard
        version: v0
    spec:
      containers:
        -
          image: quay.io/ukhomeofficedigital/hubot-decard:VERSION
          imagePullPolicy: Always
          env:
          - name: HUBOT_SLACK_TOKEN
            value: "sdcaraergergr"
          - name: HUBOT_MERGE_SPAM_ANNOUNCE_ROOMS
            value: "merges,random"
          - name: HUBOT_MERGE_SPAM_CRON
            value: "0 * */3 * * *"
          - name: HUBOT_MERGE_SPAM_GITHUB_ORGANISATION
            value: "UKHomeOffice"
          - name: HUBOT_MERGE_SPAM_GITHUB_AUTH_USERNAME
            value: "GHBot"
          - name: HUBOT_MERGE_SPAM_GITHUB_AUTH_PASSWORD
            value: "adtgethrwthwrth"
          - name: HUBOT_MERGE_SPAM_GITLAB_HOST
            value: "https://gitlab.yourhost.com"
          - name: HUBOT_MERGE_SPAM_GITLAB_API_TOKEN
            value: "fgbfynynsdrgsrg"
          name: hubot-decard
          resources:
            limits:
              memory: 500mb
      restartPolicy: Always
